baseURL = "https://erewhon.github.io/"
languageCode = "en-us"
title = "erewhon"
theme = "beautifulhugo"
# theme = "hugo-initio"
# publishDir = "docs"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-2244735-1"

[params]
    subtitle = "tech. talk. code. bacon."
    name = "Steven Byrnes"
    description = "rando"
    email = "erewhon@flatland.org"
    address = "Houston TX"
    year = "2007-2017"
    background = ""
    logo = "images/horsing_around.jpg"
    favicon = "img/favicon.ico"
    DateForm = "January 2, 2006"
    comments = false

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownload = false
    showClients = false

# [[Params.bigimg]]
#   src = "images/IMG_8386.jpg"
#   desc = "Prada"

[Author]
  name = "Steven Byrnes"
  website = "erewhon.github.io"
  # email = "youremail@domain.com"
  facebook = "erewhon"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "erewhon"
  # gitlab = "username"
  twitter = "erewhon"
  # reddit = "username"
  linkedin = "erewhon"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "prezi"
    name = "Prezi"
    url = "page/presentations/"
    weight = 2

# [[menu.main]]
#     identifier = "code"
#     name = "Codez"
#     weight = 2


# [[menu.main]]
#     name = "home"
#     url = "/"
#     weight = 1
# [[menu.main]]
#     name = "blog"
#     url = "/post/"
#     weight = 5

#[params.disqus]
#    site = "hugo-initio-site.disqus.com"

#[params.sharethis]
#    property = "123456789012345678901234"
#    custom = true

#[params.google.analytics]
#    trackerID = "GA-000000000-0"

[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/erewhon"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/erewhon"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
# [[params.social]]
#	title = "instagram"
#	url = "https://www.instagram.com/nickname"
#    icon = "fa-instagram"
#    footer = true
#    sharethis = false
#    network = ""
#[[params.social]]
#	title = "google+"
#	url = "https://plus.google.com/+nickname"
#    icon = "fa-google-plus-square"
#    footer = false
#    sharethis = true
#    network = "googleplus"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/erewhon"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
# [[params.social]]
#	title = "tumblr"
#	url = "https://nickname.tumblr.com"
#    icon = "fa-tumblr-square"
#    footer = false
#    sharethis = false
#    network = "tumblr"
[[params.social]]
    title = "github"
    url = "https://github.com/erewhon"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
# [[params.social]]
#     title = "email"
#     url = "mailto:some.email@somewhere.com"
#     icon = "fa-envelope"
#     footer = false
#     sharethis = true
#     network = "email"
